name: Build

on:
  push:
    branches-ignore: [ "release" ]
    paths-ignore: [ "**.md" ]
  pull_request:
    paths-ignore: [ "**.md" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 5
    # Only run if this isn't a PR or this is a PR not from our repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v2

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: i686-pc-windows-msvc

      - name: Build
        run: dotnet build Osu.Patcher.Injector

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: osu!patcher-debug
          if-no-files-found: error
          path: .\Osu.Patcher.Injector\bin\Debug\net8.0\**
